import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



// function untuk cek akun ada atau tidak, jika tidak ada redirect ke sign-in
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




{
  return (
    <html lang="en">
      <head>
        {/* Tambahkan link CDN Font Awesome di sini */}
        <link 
          rel="stylesheet" 
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" 
        />
        <link rel="icon" href="/favicon.ico?favicon.0b3bf435.ico" sizes="256x256" type="image/x-icon"></link>

        
      </head>

      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        
        {/* tidak bisa masuk ke root tanpa akun */}
        
        
        {children}
      </body>
    </html>
  );
}
}
